//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Eve Market Scanner")]
[assembly: AssemblyDescription("Regional comparison of marketlogs.")]
[assembly: AssemblyCompany("Eve Market Scanner")]
[assembly: AssemblyProduct("Eve Market Scanner")]
[assembly: AssemblyCopyright("Copyright © Eraggan Sadarr 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("0f95ace8-ca6c-4608-a72f-c031643be77a")]
[assembly: AssemblyVersion("1.6.0.1847")]
[assembly: AssemblyFileVersion("1.6.0.1847")]


