//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketScanner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyMarketLogPath {
            get {
                return ((string)(this["MyMarketLogPath"]));
            }
            set {
                this["MyMarketLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MyWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MyWindowState"]));
            }
            set {
                this["MyWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("990, 740")]
        public global::System.Drawing.Size MyWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MyWindowSize"]));
            }
            set {
                this["MyWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point MyWindowLoc {
            get {
                return ((global::System.Drawing.Point)(this["MyWindowLoc"]));
            }
            set {
                this["MyWindowLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MySettingsUpgradeToNewVersion {
            get {
                return ((bool)(this["MySettingsUpgradeToNewVersion"]));
            }
            set {
                this["MySettingsUpgradeToNewVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MyLoadLogsOnStartup {
            get {
                return ((bool)(this["MyLoadLogsOnStartup"]));
            }
            set {
                this["MyLoadLogsOnStartup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MyUseCacheReader
        {
            get
            {
                return ((bool)(this["MyUseCacheReader"]));
            }
            set
            {
                this["MyUseCacheReader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MyLogsDateFilterEnabled {
            get {
                return ((bool)(this["MyLogsDateFilterEnabled"]));
            }
            set {
                this["MyLogsDateFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2005-02-24")]
        public global::System.DateTime MyLogsDateFilter {
            get {
                return ((global::System.DateTime)(this["MyLogsDateFilter"]));
            }
            set {
                this["MyLogsDateFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long MinMarketQuantity {
            get {
                return ((long)(this["MinMarketQuantity"]));
            }
            set {
                this["MinMarketQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MinSystemSecurity {
            get {
                return ((double)(this["MinSystemSecurity"]));
            }
            set {
                this["MinSystemSecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MarketScanner.EveApi.EveAccount SavedEveAccount {
            get {
                return ((global::MarketScanner.EveApi.EveAccount)(this["SavedEveAccount"]));
            }
            set {
                this["SavedEveAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMarketBrowserClosed {
            get {
                return ((bool)(this["IsMarketBrowserClosed"]));
            }
            set {
                this["IsMarketBrowserClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReadConquerableStationsFromApi {
            get {
                return ((bool)(this["ReadConquerableStationsFromApi"]));
            }
            set {
                this["ReadConquerableStationsFromApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAllAvailableMarketItemsInTreeView {
            get {
                return ((bool)(this["ShowAllAvailableMarketItemsInTreeView"]));
            }
            set {
                this["ShowAllAvailableMarketItemsInTreeView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList ExeptedSystems {
            get {
                return ((global::System.Collections.ArrayList)(this["ExeptedSystems"]));
            }
            set {
                this["ExeptedSystems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreExpiredOrders {
            get {
                return ((bool)(this["IgnoreExpiredOrders"]));
            }
            set {
                this["IgnoreExpiredOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ContextMenuStrip SellersL {
            get {
                return ((global::System.Windows.Forms.ContextMenuStrip)(this["SellersL"]));
            }
            set {
                this["SellersL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ContextMenuStrip SellersR {
            get {
                return ((global::System.Windows.Forms.ContextMenuStrip)(this["SellersR"]));
            }
            set {
                this["SellersR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ContextMenuStrip BuyersL {
            get {
                return ((global::System.Windows.Forms.ContextMenuStrip)(this["BuyersL"]));
            }
            set {
                this["BuyersL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ContextMenuStrip BuyersR {
            get {
                return ((global::System.Windows.Forms.ContextMenuStrip)(this["BuyersR"]));
            }
            set {
                this["BuyersR"] = value;
            }
        }
    }
}
